version: '3.8'
services:
  localstack:
    container_name: localstack-anime-api
    image: localstack/localstack
    ports:
      - "4566-4599:4566-4599"
      - "8080:8080"
    environment:
      - SERVICES=s3,lambda,logs,dynamodb
      - DEBUG=1